import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
  future: {
    experimental_faster: true,
    v4: true,
  },
  title: "웰시고기 일기장",
  tagline: "touhouwiki-kr project",
  favicon: "img/sanae.ico",

  // Set the production url of your site here
  url: "https://t-skt.github.io",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/twiki/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "t-skt", // Usually your GitHub org/user name.
  projectName: "twiki", // Usually your repo name.
  trailingSlash: false,

  onBrokenLinks: "throw",

  markdown: {
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
  },

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "ko",
    locales: ["ko"],
  },

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars.ts",
          sidebarItemsGenerator: async (args) => {
            const hiddenDocIds = new Set<string>([
              "toy/character-canvas",
              // Note: numeric prefixes are stripped from doc ids ("2025-...").
              "toy/touhou-vote-chart",
              "toy/2025-touhou-vote-chart",
            ]);

            const generated = await args.defaultSidebarItemsGenerator(args);
            type Sidebar = typeof generated;
            type Item = Sidebar[number];

            const filterSidebar = (items: Sidebar): Sidebar => {
              const out: Item[] = [];
              for (const item of items) {
                if (item.type === "doc" || item.type === "ref") {
                  if (!hiddenDocIds.has(item.id)) out.push(item);
                  continue;
                }

                if (item.type === "category") {
                  const nextItems = filterSidebar(item.items as Sidebar);
                  if (nextItems.length === 0) continue;
                  out.push({ ...item, items: nextItems } as Item);
                  continue;
                }

                // html/link/autogenerated
                out.push(item);
              }
              return out;
            };

            return filterSidebar(generated);
          },
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl: "https://github.com/t-skt/twiki/tree/main/",
        },
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Replace with your project's social card
    image: "img/docusaurus-social-card.jpg",
    navbar: {
      title: "웰시고기 일기장",
      logo: {
        alt: "웰시고기 일기장",
        src: "img/sanae.svg",
      },
      items: [
        {
          type: "dropdown",
          label: "슈팅",
          position: "left",
          items: [
            { label: "동방홍마향 (Th06)", to: "/docs/shooting/embodiment-of-scarlet-devil/intro" },
            { label: "동방요요몽 (Th07)", to: "/docs/shooting/perfect-cherry-blossom/intro" },
            { label: "동방영야초 (Th08)", to: "/docs/shooting/imperishable-night/intro" },
            { label: "동방화영총 (Th09)", to: "/docs/shooting/phantasmagoria-of-flower-view/intro" },
            { label: "동방풍신록 (Th10)", to: "/docs/shooting/mountain-of-faith/intro" },
            { label: "동방지령전 (Th11)", to: "/docs/shooting/subterranean-animism/intro" },
            { label: "동방성련선 (Th12)", to: "/docs/shooting/undefined-fantastic-object/intro" },
            { label: "동방신령묘 (Th13)", to: "/docs/shooting/ten-desires/intro" },
            { label: "동방휘침성 (Th14)", to: "/docs/shooting/double-dealing-character/intro" },
            { label: "동방감주전 (Th15)", to: "/docs/shooting/legacy-of-lunatic-kingdom/intro" },
            { label: "동방천공장 (Th16)", to: "/docs/shooting/hidden-star-in-four-seasons/intro" },
            { label: "동방귀형수 (Th17)", to: "/docs/shooting/wily-beast-and-weakest-creature/intro" },
            { label: "동방홍룡동 (Th18)", to: "/docs/shooting/unconnected-marketeers/intro" },
            { label: "동방금상경 (Th20)", to: "/docs/shooting/fossilized-wonders/intro" },
          ],
        },
        {
          type: "dropdown",
          label: "격투",
          position: "left",
          items: [
            { label: "동방췌몽상 (Th075)", to: "/docs/fighting/immaterial-and-missing-power/intro" },
            { label: "동방비상천 (Th105)", to: "/docs/fighting/scarlet-weather-rhapsody/intro" },
            { label: "동방비상천칙 (Th123)", to: "/docs/fighting/hisoutensoku/intro" },
            { label: "동방심기루 (Th135)", to: "/docs/fighting/hopeless-masquerade/intro" },
            { label: "동방심비록 (Th145)", to: "/docs/fighting/urban-legend-in-limbo/intro" },
            { label: "동방빙의화 (Th155)", to: "/docs/fighting/antinomy-of-common-flowers/intro" },
            { label: "동방강욕이문 (Th175)", to: "/docs/fighting/touhou-gouyoku-ibun/intro" },
            { label: "동방수왕원 (Th19)", to: "/docs/fighting/unfinished-dream-of-all-living-ghost/intro" },
          ],
        },
        {
          type: "dropdown",
          label: "외전",
          position: "left",
          items: [
            { label: "동방문화첩 (Th095)", to: "/docs/side/shoot-the-bullet/intro" },
            { label: "더블 스포일러 (Th125)", to: "/docs/side/double-spoiler/intro" },
            { label: "요정대전쟁 (Th128)", to: "/docs/side/great-fairy-wars/intro" },
            { label: "탄막 아마노자쿠 (Th143)", to: "/docs/side/impossible-spell-card/intro" },
            { label: "비봉 나이트메어 다이어리 (Th165)", to: "/docs/side/violet-detector/intro" },
            { label: "불릿필리아들의 암시장 (Th185)", to: "/docs/side/bullet-filia/intro" },
          ],
        },
        {
          type: "dropdown",
          label: "음악",
          position: "left",
          items: [
            { label: "전체 앨범", to: "/docs/music" },
            { label: "Dolls in Pseudo Paradise", to: "/docs/music/dolls-in-pseudo-paradise" },
            { label: "Ghostly Field Club", to: "/docs/music/ghostly-field-club" },
            { label: "Changeability of Strange Dream", to: "/docs/music/changeability-of-strange-dream" },
            { label: "Retrospective 53 minutes", to: "/docs/music/retrospective-53-minutes" },
            { label: "Magical Astronomy", to: "/docs/music/magical-astronomy" },
            { label: "Unknown Flower Mesmerizing Journey", to: "/docs/music/unknown-flower-mesmerizing-journey" },
            { label: "Trojan Green Asteroid", to: "/docs/music/trojan-green-asteroid" },
            { label: "Neo-traditionalism of Japan", to: "/docs/music/neo-traditionalism-of-japan" },
            { label: "Dr. Latency's Freak Report", to: "/docs/music/dr-latencys-freak-report" },
            { label: "Dateless Bar Old Adam", to: "/docs/music/dateless-bar-old-adam" },
            { label: "Rainbow-Colored Septentrion", to: "/docs/music/rainbow-colored-septentrion" },
            { label: "Taboo Japan Disentanglement", to: "/docs/music/taboo-japan-disentanglement" },
          ],
        },
        {
          href: "https://github.com/t-skt/twiki",
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Docs",
          items: [
            {
              label: "동방",
              to: "/docs/shooting/embodiment-of-scarlet-devil/intro",
            },
          ],
        },
        {
          title: "Editor",
          items: [
            {
              label: "X",
              href: "https://x.com/wealthygogi",
            },
          ],
        },
      ],
      copyright: `Copyleft © ${new Date().getFullYear()} @wealthygogi. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
