import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  gameSidebar: [
    {
      type: "category",
      label: "슈팅",
      link: {
        type: "generated-index",
        title: "슈팅 게임",
        description: "동방 프로젝트 메인 슈팅 시리즈.",
      },
      items: [{ type: "autogenerated", dirName: "shooting" }],
    },
    {
      type: "category",
      label: "격투",
      link: {
        type: "generated-index",
        title: "격투 게임",
        description: "동방 프로젝트 격투 게임.",
      },
      items: [{ type: "autogenerated", dirName: "fighting" }],
    },
    {
      type: "category",
      label: "외전",
      link: {
        type: "generated-index",
        title: "외전 게임",
        description: "동방 프로젝트 외전 작품.",
      },
      items: [{ type: "autogenerated", dirName: "side" }],
    },
  ],
};

export default sidebars;
