import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  gameSidebar: [
    {
      type: "category",
      label: "슈팅",
      link: { type: "generated-index" },
      items: [
        {
          type: "category",
          label: "동방홍마향",
          link: {
            type: "doc",
            id: "shooting/embodiment-of-scarlet-devil/intro",
          },
          items: [
            "shooting/embodiment-of-scarlet-devil/intro",
            {
              type: "autogenerated",
              dirName: "shooting/embodiment-of-scarlet-devil/characters",
            },
            "shooting/embodiment-of-scarlet-devil/music",
          ],
        },
      ],
    },
  ],
};

export default sidebars;
