import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Each game gets its own sidebar — autogenerated from its docs/ subdir.
// Frontmatter `displayed_sidebar` on each mdx routes the page to the right sidebar.
const sidebars: SidebarsConfig = {
  // ── 슈팅 (15 games) ──
  th06Sidebar: [{ type: "autogenerated", dirName: "shooting/embodiment-of-scarlet-devil" }],
  th07Sidebar: [{ type: "autogenerated", dirName: "shooting/perfect-cherry-blossom" }],
  th08Sidebar: [{ type: "autogenerated", dirName: "shooting/imperishable-night" }],
  th09Sidebar: [{ type: "autogenerated", dirName: "shooting/phantasmagoria-of-flower-view" }],
  th10Sidebar: [{ type: "autogenerated", dirName: "shooting/mountain-of-faith" }],
  th11Sidebar: [{ type: "autogenerated", dirName: "shooting/subterranean-animism" }],
  th12Sidebar: [{ type: "autogenerated", dirName: "shooting/undefined-fantastic-object" }],
  th13Sidebar: [{ type: "autogenerated", dirName: "shooting/ten-desires" }],
  th14Sidebar: [{ type: "autogenerated", dirName: "shooting/double-dealing-character" }],
  th15Sidebar: [{ type: "autogenerated", dirName: "shooting/legacy-of-lunatic-kingdom" }],
  th16Sidebar: [{ type: "autogenerated", dirName: "shooting/hidden-star-in-four-seasons" }],
  th17Sidebar: [{ type: "autogenerated", dirName: "shooting/wily-beast-and-weakest-creature" }],
  th18Sidebar: [{ type: "autogenerated", dirName: "shooting/unconnected-marketeers" }],
  th19Sidebar: [{ type: "autogenerated", dirName: "shooting/unfinished-dream-of-all-living-ghost" }],
  th20Sidebar: [{ type: "autogenerated", dirName: "shooting/fossilized-wonders" }],

  // ── 격투 (7 games) ──
  th075Sidebar: [{ type: "autogenerated", dirName: "fighting/immaterial-and-missing-power" }],
  th105Sidebar: [{ type: "autogenerated", dirName: "fighting/scarlet-weather-rhapsody" }],
  th123Sidebar: [{ type: "autogenerated", dirName: "fighting/hisoutensoku" }],
  th135Sidebar: [{ type: "autogenerated", dirName: "fighting/hopeless-masquerade" }],
  th145Sidebar: [{ type: "autogenerated", dirName: "fighting/urban-legend-in-limbo" }],
  th155Sidebar: [{ type: "autogenerated", dirName: "fighting/antinomy-of-common-flowers" }],
  th175Sidebar: [{ type: "autogenerated", dirName: "fighting/touhou-gouyoku-ibun" }],

  // ── 외전 (6 games) ──
  th095Sidebar: [{ type: "autogenerated", dirName: "side/shoot-the-bullet" }],
  th125Sidebar: [{ type: "autogenerated", dirName: "side/double-spoiler" }],
  th128Sidebar: [{ type: "autogenerated", dirName: "side/great-fairy-wars" }],
  th143Sidebar: [{ type: "autogenerated", dirName: "side/impossible-spell-card" }],
  th165Sidebar: [{ type: "autogenerated", dirName: "side/violet-detector" }],
  th185Sidebar: [{ type: "autogenerated", dirName: "side/bullet-filia" }],

  // ── 음악 (single sidebar; album mdx files share it) ──
  musicSidebar: [{ type: "autogenerated", dirName: "music" }],
};

export default sidebars;
